model:
  base_model_name: "microsoft/Phi-3-vision-128k-instruct"
  fine_tuned_path: "./artifacts/phi3_vision_finetuned.pth"
  quantized_path: "./artifacts/phi3_vision_quantized.pth"
  coreml_output_path: "./artifacts/AuraModel.mlmodel"

data:
  dataset_name: "pcuenq/oxford-pets"

training:
  num_epochs: 3
  learning_rate: 1e-5
  batch_size_per_device: 2