# config.yaml

model:
  base_model_name: "microsoft/Phi-3-vision-128k-instruct" # <-- THE FIX IS HERE
  fine_tuned_path: "./artifacts/fine_tuned_model"
  quantized_path: "./artifacts/quantized_model"
  coreml_output_path: "./artifacts/AuraModel.mlmodel"

data:
  dataset_name: "pcuenq/oxford-pets"
  local_path: "./data"

training:
  num_epochs: 3
  learning_rate: 1e-5
  batch_size_per_device: 2 # <-- Start with a smaller batch size for safety